---
title: "practice with strings"
format: html
editor: visual
---

```{r}
alarm_report <- data.frame(
  stringsAsFactors = FALSE,
              date = c("2020-03-14", "2020-03-15", "2020-04-10", "2020-04-18"),
          building = c("Engineering-North",
                       "Bren Hall","Engineering-South","Engr-North"),
     alarm_message = c("10:02am – HVAC system down, facilities management alerted",
                       "8:24am – Elevator North out of service",
                       "12:41am – Fire alarm, UCSB fire responded and cleared",
                       "9:58pm – Campus point emergency siren, UCPD responded")
)
```

```{r}
# replace the "Engr" with "engineering in the building column
alarm_report <- alarm_report %>% 
  mutate(building = str_replace(building, pattern = "Engr", replacement = "Engineering"))

# separate the building column into two separate columns, building and wing, separated at the dash
alarm_report <- alarm_report %>% 
  separate(building, into = c("building", "wing"),
           sep = "-") 

# only keep observations with the word "responded" in the alarm_message column
alarm_report <- alarm_report %>% 
  filter(str_detect(alarm_message, pattern = "responded"))

# separate the message "time" from the rest of the message by separating at --
alarm_report <- alarm_report %>% 
  separate(alarm_message, c("time", "alarm_message"), "–")

# convert the data column to a date class using lubridate
alarm_report <- alarm_report %>% 
  mutate(date = lubridate::ymd(date))
```
